/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_healthCheck"];
  };
  "/auth/login": {
    post: operations["AuthController_login"];
  };
  "/auth/admin/login": {
    post: operations["AuthController_adminLogin"];
  };
  "/auth/register": {
    post: operations["AuthController_register"];
  };
  "/auth/refresh": {
    post: operations["AuthController_refreshTokens"];
  };
  "/auth/me": {
    get: operations["AuthController_me"];
  };
  "/actions/create": {
    post: operations["ActionsController_create"];
  };
  "/actions/{id}": {
    get: operations["ActionsController_findOne"];
    post: operations["ActionsController_join"];
    delete: operations["ActionsController_remove"];
    patch: operations["ActionsController_update"];
  };
  "/actions": {
    get: operations["ActionsController_findAll"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignInDto: {
      email: string;
      password: string;
    };
    SignUp: {
      name: string;
      email: string;
      password: string;
    };
    CreateActionDto: {
      name: string;
      category: string;
      whyJoin: string;
      type: string;
      description: string;
      /** @enum {string} */
      status: "Active" | "Upcoming" | "Past" | "Draft";
    };
    UpdateActionDto: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  AppController_healthCheck: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: never;
      };
      /** @description Invalid credentials */
      401: {
        content: never;
      };
    };
  };
  AuthController_adminLogin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: never;
      };
      /** @description Invalid credentials */
      401: {
        content: never;
      };
    };
  };
  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUp"];
      };
    };
    responses: {
      /** @description User created successfully */
      201: {
        content: never;
      };
      /** @description Invalid credentials */
      401: {
        content: never;
      };
    };
  };
  AuthController_refreshTokens: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_me: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActionsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ActionsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActionsController_join: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ActionsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActionsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActionDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActionsController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
}
