// This file is auto-generated by @hey-api/openapi-ts

export type SignInDto = {
    password: string;
    mode: 'cookie' | 'header';
    email: string;
};

export type SignInResponseDto = {
    isAdmin: boolean;
    access_token?: string;
    refresh_token?: string;
};

export type TokenMode = 'cookie' | 'header';

export type SignUpDto = {
    name: string;
    email: string;
    password: string;
    mode: TokenMode;
    referralCode?: string;
};

export type AccessToken = {
    access_token: string;
};

export type NotificationPreference = 'all' | 'digest' | 'none';

export type ForumDigestPreference = 'off' | 'daily' | 'weekly';

export type ProfileDto = {
    id: number;
    contractDateSigned: string | null;
    admin: boolean;
    staff: boolean;
    profilePicture: string | null;
    profileDescription: string | null;
    displayName: string;
};

export type UserDto = {
    id: number;
    name: string;
    phoneNumber?: string;
    contractDateSigned: string | null;
    contractDateSuspended: string | null;
    emailNotifsEnabled: boolean;
    textNotifsEnabled: boolean;
    pushNotifsEnabled: boolean;
    socialNotifsPreference: NotificationPreference;
    turnedOffAllNotifs: boolean;
    forumDigestPreference: ForumDigestPreference;
    admin: boolean;
    staff: boolean;
    referralCode: string | null;
    onboardingComplete: boolean;
    anonymous: boolean;
    cityId?: number;
    friends: Array<ProfileDto>;
    email: string;
};

export type ForgotPasswordDto = {
    email: string;
};

export type ResetPasswordDto = {
    token: string;
    password: string;
};

export type OnboardingDto = {
    over18: boolean | null;
    anonymous: boolean;
    cityId?: number;
};

export type CreateAwayRangeDto = {
    note?: string | null;
    startDay: string;
    endDay: string;
};

export type UserAwayRangeDto = {
    id: number;
    startDate: string;
    endDate: string;
    createdAt: string;
    note?: string | null;
};

export type PlainTime = {
    [key: string]: unknown;
};

export type UpdateProfileDto = {
    id?: number;
    name?: string;
    phoneNumber?: string;
    phoneNumberValidated?: boolean;
    sentTextOptInMessageAt?: string;
    emailVerified?: boolean;
    preferredReminderTime?: PlainTime;
    timeZone?: {
        [key: string]: unknown;
    };
    contractDateSigned?: string | null;
    contractDateSuspended?: string | null;
    emailNotifsEnabled?: boolean;
    textNotifsEnabled?: boolean;
    pushNotifsEnabled?: boolean;
    socialNotifsPreference?: NotificationPreference;
    turnedOffAllNotifs?: boolean;
    forumDigestPreference?: ForumDigestPreference;
    password?: string;
    admin?: boolean;
    staff?: boolean;
    profilePicture?: string | null;
    profileDescription?: string | null;
    referralCode?: string | null;
    stripeCustomerId?: string | null;
    isNotSignedUpPartialProfile?: boolean;
    over18?: boolean | null;
    onboardingComplete?: boolean;
    anonymous?: boolean;
    cityId?: number;
};

export type City = {
    id: number;
    name: string;
    admin1: string;
    admin2: string;
    countryCode: string;
    countryName: string;
    latitude: number;
    longitude: number;
};

export type FriendStatus = 'pending' | 'accepted' | 'declined' | 'none';

export type FriendStatusDto = {
    status: FriendStatus | null;
    didReceiveRequest: boolean;
};

export type User = {
    id: number;
    name: string;
    phoneNumber?: string;
    phoneNumberValidated: boolean;
    sentTextOptInMessageAt?: string;
    emailVerified: boolean;
    preferredReminderTime?: PlainTime;
    timeZone?: {
        [key: string]: unknown;
    };
    contractDateSigned: string | null;
    contractDateSuspended: string | null;
    emailNotifsEnabled: boolean;
    textNotifsEnabled: boolean;
    pushNotifsEnabled: boolean;
    socialNotifsPreference: NotificationPreference;
    turnedOffAllNotifs: boolean;
    forumDigestPreference: ForumDigestPreference;
    password: string;
    admin: boolean;
    staff: boolean;
    profilePicture: string | null;
    profileDescription: string | null;
    referralCode: string | null;
    stripeCustomerId: string | null;
    isNotSignedUpPartialProfile: boolean;
    over18: boolean | null;
    onboardingComplete: boolean;
    anonymous: boolean;
};

export type ActionStatus = 'draft' | 'upcoming' | 'gathering_commitments' | 'office_action' | 'member_action' | 'resolution' | 'completed' | 'failed' | 'abandoned';

export type UserActionSummaryDto = {
    id: number;
    name: string;
    status: ActionStatus;
};

export type UserActionRelationStatus = 'none' | 'joined' | 'completed' | 'declined' | 'wont_complete' | 'missed_deadline';

export type ActionActivityType = 'user_joined' | 'user_completed' | 'user_declined' | 'user_wont_complete';

export type UserActionRelationDetailDto = {
    actionId: number;
    status: UserActionRelationStatus;
    latestActivityType?: ActionActivityType;
    latestActivityAt?: string;
};

export type UserActionRelationsForUserDto = {
    userId: number;
    relations: Array<UserActionRelationDetailDto>;
};

export type UserActionRelationsResponseDto = {
    actions: Array<UserActionSummaryDto>;
    users: Array<UserActionRelationsForUserDto>;
};

export type ProfileDtoWithFriends = {
    id: number;
    contractDateSigned: string | null;
    admin: boolean;
    staff: boolean;
    profilePicture: string | null;
    profileDescription: string | null;
    displayName: string;
    friends: Array<ProfileDto>;
};

export type VerifyEmailBody = {
    [key: string]: unknown;
};

export type CreateGroupDto = {
    name: string;
    description: string;
    publicDisplayName?: string;
};

export type GroupDto = {
    id: number;
    name: string;
    description: string;
    publicDisplayName?: string;
    createdAt: string;
    updatedAt: string;
    users: Array<ProfileDto>;
};

export type AddUserToGroupDto = {
    userId: number;
};

export type CreateOnetimeInviteDto = {
    invitee: string;
    invitingUserId: number;
};

export type OnetimeInviteDto = {
    id: number;
    invitee: string;
    code: string;
    invitingUser: User;
    createdAt: string;
    isValid: boolean;
};

export type StreamableFile = {
    [key: string]: unknown;
};

export type UploadImageResponseDto = {
    url: string;
    key: string;
};

export type CommentParentObject = 'post' | 'action' | 'activity';

export type EditableContentDto = {
    /**
     * Markdown or plain text body
     */
    body: string;
    /**
     * Image keys attached to the content
     */
    attachments: Array<string>;
};

export type CommentDto = {
    id: number;
    parentObjectType: CommentParentObject;
    parentObjectId: number;
    deleted: boolean;
    createdAt: string;
    updatedAt: string;
    parentId?: number;
    pinned: boolean;
    author: ProfileDto;
    children?: Array<CommentDto>;
    likes: Array<ProfileDto>;
    editableContent: EditableContentDto;
};

export type ActionActivityDto = {
    id: number;
    /**
     * Type of action activity
     */
    type: ActionActivityType;
    actionId: number;
    createdAt: string;
    user: ProfileDto;
    actionName: string;
    likes: Array<ProfileDto>;
    comments: Array<CommentDto>;
    editableContent: EditableContentDto;
};

export type DeclineActionDto = {
    reason: string;
    moral: boolean;
};

export type OptOutActionDto = {
    reason: string;
    outOfTime: boolean;
};

export type UserActionRelation = 'joined' | 'completed' | 'none' | 'declined';

export type UserActionRelationDto = {
    relation: UserActionRelation;
};

/**
 * Type of the action
 */
export type ActionTaskType = 'Funding' | 'Activity' | 'Ongoing';

export type EditableContent = {
    /**
     * Markdown or plain text body
     */
    body: string;
    /**
     * Image keys attached to the content
     */
    attachments: Array<string>;
};

export type ActionUpdateNotifyType = 'none' | 'bell_participants' | 'bell_all_members';

export type NotificationCategory = 'action_event' | 'forum_reply' | 'friend_request' | 'friend_request_accepted' | 'action_update';

export type Notification = {
    id: number;
    category: NotificationCategory;
    message: string;
    webAppLocation: string | null;
    mobileAppLocation: string | null;
    read: boolean;
    cleared: boolean;
    createdAt: string;
    updatedAt: string;
    actionUpdate?: ActionUpdate;
};

export type ActionUpdate = {
    id: number;
    action: Action;
    title: string;
    content: EditableContent;
    displayDate: string;
    visibleAt: string;
    associatedEvent?: ActionEvent;
    notifyType: ActionUpdateNotifyType;
    notifs: Array<Notification>;
};

export type ActionEvent = {
    /**
     * Unique identifier for the action event
     */
    id: number;
    /**
     * Title of the event
     */
    title: string;
    /**
     * secondary text
     */
    description: string;
    /**
     * New status of the action after the event
     */
    newStatus: ActionStatus;
    /**
     * time of the event (for display)
     */
    date: string;
    /**
     * Timestamp when the event was last updated
     */
    updatedAt: string;
    /**
     * Indicates whether the event should be shown in the timeline
     */
    showInTimeline: boolean;
    /**
     * The action associated with this event
     */
    action: Action;
    updates: Array<ActionUpdate>;
    suiteManaged: boolean;
};

export type FormResponse = {
    id: number;
    formId: number;
    answers: {
        [key: string]: unknown;
    };
    visibilityValidatorResults: {
        [key: string]: unknown;
    };
    user: User;
    createdAt: string;
    schemaSnapshot: {
        [key: string]: unknown;
    };
};

export type ActionActivity = {
    id: number;
    /**
     * Type of action activity
     */
    type: ActionActivityType;
    actionId: number;
    userId: number;
    createdAt: string;
    dollar_amount?: number;
    editableContent?: EditableContent;
    likes: Array<User>;
    taskFormResponse?: FormResponse;
    declineReason?: string;
    isMoral?: boolean;
    outOfTime?: boolean;
};

export type ReminderGroupTimingMode = 'absolute' | 'from_deadline' | 'within_range' | 'event_launch';

export type ReminderCohortType = 'all_uncompleted' | 'group' | 'custom';

export type ActionEventNotifType = 'announcement' | 'misseddeadline' | 'reminder' | 'personalreminder';

export type NotificationChannel = 'text' | 'email' | 'push';

export type EmailType = 'verification' | 'password_reset' | 'partial_signup' | 'welcome' | 'other' | 'commitment' | 'memberaction' | 'commitmentreminder' | 'memberactionreminder' | 'forum_digest' | 'missed_deadline' | 'missed_second_deadline' | 'custom_action_reminder';

export type Mail = {
    id: number;
    sentMessageId?: string;
    renderedHtml?: string;
    to: string;
    status: string;
    emailType: EmailType;
    createdAt: string;
    cid?: string;
    clickedLink: boolean;
};

export type Mms = {
    id: number;
    to: string;
    from: string;
    body: string;
    status: string;
    twilioSid: string;
    errorCode?: number;
    errorMessage?: string;
    createdAt: string;
    updatedAt: string;
    cid?: string;
    clickedLink: boolean;
};

export type ActionEventNotif = {
    id: number;
    type: ActionEventNotifType;
    channel: NotificationChannel;
    mail: Mail | null;
    mms: Mms | null;
    reminderGroup?: ReminderGroup;
    /**
     * Indicates whether the notification has been sent
     */
    sent: boolean;
    idempotency_key?: string;
    createdAt: string;
};

export type ReminderGroup = {
    id: number;
    name: string;
    timingMode: ReminderGroupTimingMode;
    actionSuite?: ActionSuite;
    memberActionEvent: ActionEvent;
    cohortType: ReminderCohortType;
    userGroup?: Group;
    users?: Array<User>;
    emailMessage: string;
    emailSubject: string;
    textMessage: string;
    notifications: Array<ActionEventNotif>;
    send_range_start?: string;
    send_range_end?: string;
    sendAtAbsolute?: string;
    sendAtSecondsFromDeadline?: number;
    deadlineEvent?: ActionEvent;
    allSent: boolean;
};

export type ActionSuite = {
    id: number;
    name: string;
    actions: Array<Array<unknown>>;
    reminderGroups: Array<ReminderGroup>;
    createdAt: string;
    updatedAt: string;
    events: Array<ActionEvent>;
};

export type Action = {
    /**
     * Unique identifier for the action
     */
    id: number;
    /**
     * Name of the action
     */
    name: string;
    /**
     * Category of the action
     */
    category: string;
    /**
     * Image URL for the action
     */
    image?: string;
    /**
     * Number of commitments needed to start the action
     */
    commitmentThreshold?: number;
    /**
     * Suggested donation amount (cents)
     */
    donationAmount?: number;
    /**
     * e.g. onboarding
     */
    commitmentless: boolean;
    /**
     * markdown page body
     */
    body: string;
    /**
     * markdown contents for activity task card (instructions)
     */
    taskContents?: string;
    /**
     * Short description shown in cards
     */
    shortDescription: string;
    /**
     * Time estimate in minutes
     */
    timeEstimate?: number;
    /**
     * Type of the action
     */
    type: ActionTaskType;
    /**
     * Form associated with the action
     */
    taskFormId?: number;
    /**
     * Timestamp when the action was created
     */
    createdAt: string;
    /**
     * Timestamp when the action was last updated
     */
    updatedAt: string;
    /**
     * Events associated with the action
     */
    events: Array<ActionEvent>;
    participatingGroups: Array<Group>;
    /**
     * Whether to show the action to members who are not of participating groups
     */
    showToNonparticipating?: boolean;
    /**
     * Number of users who have joined the action
     */
    usersJoined: number;
    activities: Array<Array<ActionActivity>>;
    status: ActionStatus;
    /**
     * Number of users who have completed the action
     */
    usersCompleted: number;
    /**
     * Override default contract signing requirements for showing in tasks (e.g. for onboarding actions)
     */
    everyoneShouldComplete: boolean;
    archived: boolean;
    updates: Array<ActionUpdate>;
    suite?: ActionSuite;
    /**
     * Priority of the action
     */
    priority: number;
};

export type Group = {
    id: number;
    users: Array<User>;
    participatingIn: Array<Action>;
    name: string;
    description: string;
    publicDisplayName?: string;
    createdAt: string;
    updatedAt: string;
};

export type ActionEventDto = {
    /**
     * Unique identifier for the action event
     */
    id: number;
    /**
     * Title of the event
     */
    title: string;
    /**
     * secondary text
     */
    description: string;
    /**
     * New status of the action after the event
     */
    newStatus: ActionStatus;
    /**
     * time of the event (for display)
     */
    date: string;
    /**
     * Indicates whether the event should be shown in the timeline
     */
    showInTimeline: boolean;
    suiteManaged: boolean;
};

export type ActionDto = {
    /**
     * Unique identifier for the action
     */
    id: number;
    /**
     * Name of the action
     */
    name: string;
    /**
     * Category of the action
     */
    category: string;
    /**
     * Image URL for the action
     */
    image?: string;
    /**
     * Number of commitments needed to start the action
     */
    commitmentThreshold?: number;
    /**
     * Suggested donation amount (cents)
     */
    donationAmount?: number;
    /**
     * e.g. onboarding
     */
    commitmentless: boolean;
    /**
     * markdown page body
     */
    body: string;
    /**
     * markdown contents for activity task card (instructions)
     */
    taskContents?: string;
    /**
     * Short description shown in cards
     */
    shortDescription: string;
    /**
     * Time estimate in minutes
     */
    timeEstimate?: number;
    /**
     * Type of the action
     */
    type: ActionTaskType;
    /**
     * Form associated with the action
     */
    taskFormId?: number;
    participatingGroups: Array<Group>;
    /**
     * Whether to show the action to members who are not of participating groups
     */
    showToNonparticipating?: boolean;
    /**
     * Number of users who have joined the action
     */
    usersJoined: number;
    activities: Array<Array<ActionActivity>>;
    status: ActionStatus;
    /**
     * Number of users who have completed the action
     */
    usersCompleted: number;
    /**
     * Override default contract signing requirements for showing in tasks (e.g. for onboarding actions)
     */
    everyoneShouldComplete: boolean;
    archived: boolean;
    updates: Array<ActionUpdate>;
    suite?: ActionSuite;
    /**
     * Priority of the action
     */
    priority: number;
    events: Array<ActionEventDto>;
    canParticipate?: boolean;
    shouldParticipate?: boolean;
    userRelation?: string;
    reqAuthenticated?: boolean;
};

export type LatLonDto = {
    latitude: number;
    longitude: number;
};

export type NotificationScheduleMetadataDto = {
    currentEventId?: number;
    nextEventId?: number;
    deadlineEventId?: number;
    isSecondMiss?: boolean;
    reminderId?: number;
};

export type NotificationScheduleEntryDto = {
    type: ActionEventNotifType;
    scheduledFor: string;
    actionId: number;
    actionName: string;
    actionStatus: ActionStatus;
    eventId: number;
    recipients: Array<ProfileDto>;
    metadata?: NotificationScheduleMetadataDto;
};

export type CreateActionDto = {
    /**
     * Name of the action
     */
    name: string;
    /**
     * Category of the action
     */
    category: string;
    /**
     * Image URL for the action
     */
    image?: string;
    /**
     * Number of commitments needed to start the action
     */
    commitmentThreshold?: number;
    /**
     * Suggested donation amount (cents)
     */
    donationAmount?: number;
    /**
     * e.g. onboarding
     */
    commitmentless: boolean;
    /**
     * markdown page body
     */
    body: string;
    /**
     * Short description shown in cards
     */
    shortDescription: string;
    /**
     * Time estimate in minutes
     */
    timeEstimate?: number;
    /**
     * Type of the action
     */
    type: ActionTaskType;
    /**
     * Form associated with the action
     */
    taskFormId?: number;
    participatingGroups: Array<Group>;
    /**
     * Whether to show the action to members who are not of participating groups
     */
    showToNonparticipating?: boolean;
    /**
     * Override default contract signing requirements for showing in tasks (e.g. for onboarding actions)
     */
    everyoneShouldComplete: boolean;
    /**
     * Priority of the action
     */
    priority: number;
    canParticipate?: boolean;
    shouldParticipate?: boolean;
    userRelation?: string;
    reqAuthenticated?: boolean;
    suiteId?: number;
};

export type UpdateActionDto = {
    /**
     * Name of the action
     */
    name?: string;
    /**
     * Category of the action
     */
    category?: string;
    /**
     * Image URL for the action
     */
    image?: string;
    /**
     * Number of commitments needed to start the action
     */
    commitmentThreshold?: number;
    /**
     * Suggested donation amount (cents)
     */
    donationAmount?: number;
    /**
     * e.g. onboarding
     */
    commitmentless?: boolean;
    /**
     * markdown page body
     */
    body?: string;
    /**
     * Short description shown in cards
     */
    shortDescription?: string;
    /**
     * Time estimate in minutes
     */
    timeEstimate?: number;
    /**
     * Type of the action
     */
    type?: ActionTaskType;
    /**
     * Form associated with the action
     */
    taskFormId?: number;
    participatingGroups?: Array<Group>;
    /**
     * Whether to show the action to members who are not of participating groups
     */
    showToNonparticipating?: boolean;
    /**
     * Override default contract signing requirements for showing in tasks (e.g. for onboarding actions)
     */
    everyoneShouldComplete?: boolean;
    /**
     * Priority of the action
     */
    priority?: number;
    canParticipate?: boolean;
    shouldParticipate?: boolean;
    userRelation?: string;
    reqAuthenticated?: boolean;
    suiteId?: number;
};

export type CreateActionEventDto = {
    /**
     * Title of the event
     */
    title: string;
    /**
     * secondary text
     */
    description: string;
    /**
     * New status of the action after the event
     */
    newStatus: ActionStatus;
    /**
     * time of the event (for display)
     */
    date: string;
    /**
     * Indicates whether the event should be shown in the timeline
     */
    showInTimeline: boolean;
};

export type CreateTodReminderGroupDto = {
    name: string;
    timingMode: ReminderGroupTimingMode;
    cohortType: ReminderCohortType;
    emailMessage: string;
    emailSubject: string;
    textMessage: string;
    send_range_start?: string;
    send_range_end?: string;
    sendAtAbsolute?: string;
    sendAtSecondsFromDeadline?: number;
    userIds?: Array<number>;
    userGroupId?: number;
    suiteId?: number;
};

export type NotificationPlan = {
    scheduledFor: string;
    user: User;
};

export type ActionEventNotifDto = {
    id: number;
    type: ActionEventNotifType;
    channel: NotificationChannel;
    mail: Mail | null;
    mms: Mms | null;
    reminderGroup?: ReminderGroup;
    /**
     * Indicates whether the notification has been sent
     */
    sent: boolean;
    idempotency_key?: string;
    createdAt: string;
    user: ProfileDto;
};

export type CreateEditableContentDto = {
    /**
     * Markdown or plain text body
     */
    body: string;
    /**
     * Image keys attached to the content
     */
    attachments: Array<string>;
};

export type CreateCommentDto = {
    parentObjectType: CommentParentObject;
    parentObjectId: number;
    parentId?: number;
    editableContent: CreateEditableContentDto;
};

export type UpdateActionActivityDto = {
    editableContent: EditableContentDto;
};

export type NotificationType = 'all' | 'joined' | 'none';

export type PreEventNotifDataDto = {
    emails: Array<UserDto>;
    texts: Array<UserDto>;
    pushes: Array<UserDto>;
};

export type CreateActionActivityDto = {
    /**
     * Type of action activity
     */
    type: ActionActivityType;
    actionId: number;
    userId: number;
};

export type CreateActionUpdateDto = {
    title: string;
    displayDate: string;
    visibleAt: string;
    notifyType: ActionUpdateNotifyType;
    content: CreateEditableContentDto;
    associatedEventId?: number;
};

export type ActionSuiteDto = {
    id: number;
    name: string;
    reminderGroups: Array<ReminderGroup>;
    createdAt: string;
    updatedAt: string;
    events: Array<ActionEvent>;
    actions: Array<ActionDto>;
};

export type CreateActionSuiteDto = {
    name: string;
};

export type UpdateActionEventDto = {
    /**
     * Title of the event
     */
    title?: string;
    /**
     * secondary text
     */
    description?: string;
    /**
     * New status of the action after the event
     */
    newStatus?: ActionStatus;
    /**
     * time of the event (for display)
     */
    date?: string;
    /**
     * Indicates whether the event should be shown in the timeline
     */
    showInTimeline?: boolean;
};

export type NotificationDto = {
    id: number;
    category: NotificationCategory;
    message: string;
    webAppLocation: string | null;
    mobileAppLocation: string | null;
    read: boolean;
    cleared: boolean;
    createdAt: string;
    updatedAt: string;
    associatedUser?: ProfileDto;
};

export type NotifClickDto = {
    [key: string]: unknown;
};

export type NotifClickResponseDto = {
    mms: boolean;
};

export type CreatePostDto = {
    title: string;
    actionId?: number;
    visibleAt?: string;
    editableContent: CreateEditableContentDto;
};

export type PostDto = {
    id: number;
    title: string;
    authorId: number;
    actionId?: number;
    createdAt: string;
    pinned: boolean;
    updatedAt: string;
    visibleAt?: string;
    action?: ActionDto;
    author: ProfileDto;
    commentCount?: number;
    editableContent: EditableContentDto;
    likes: Array<ProfileDto>;
    lastComment?: CommentDto;
};

export type UserCommentDto = {
    id: number;
    parentObjectType: CommentParentObject;
    parentObjectId: number;
    deleted: boolean;
    createdAt: string;
    updatedAt: string;
    parentId?: number;
    pinned: boolean;
    author: ProfileDto;
    children?: Array<CommentDto>;
    likes: Array<ProfileDto>;
    editableContent: EditableContentDto;
    parentTitle?: string;
};

export type UpdatePostDto = {
    title?: string;
    actionId?: number;
    visibleAt?: string;
    editableContent?: CreateEditableContentDto;
};

export type UpdateCommentDto = {
    parentObjectType?: CommentParentObject;
    parentObjectId?: number;
    parentId?: number;
    editableContent?: CreateEditableContentDto;
};

export type CitySearchDto = {
    id: number;
    name: string;
    admin1: string;
    countryCode: string;
    countryName: string;
};

export type CreatePaymentIntentDto = {
    actionId: number;
};

export type ClientSecretDto = {
    clientSecret: string;
    userToken?: string;
    savedPaymentMethodId?: string;
    savedPaymentMethodLast4?: string;
    amount?: number;
};

export type CreatePartialProfileDto = {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
};

export type PaymentMethodDto = {
    id: string;
    type: string;
    brand: string;
    last4: string;
    exp_month: number;
    exp_year: number;
};

export type TableMetadataDto = {
    name: string;
    entityName: string;
    recordCount: number;
    primaryKey: string;
};

export type TableListDto = {
    tables: Array<TableMetadataDto>;
};

/**
 * Semantic data type of the column
 */
export type ColumnDataType = 'string' | 'number' | 'boolean' | 'date' | 'datetime' | 'json' | 'uuid' | 'enum' | 'relation' | 'unknown';

export type ColumnMetadataDto = {
    /**
     * Column name in the database
     */
    name: string;
    /**
     * Semantic data type of the column
     */
    dataType: ColumnDataType;
    /**
     * Raw TypeORM column type
     */
    rawType: string;
    /**
     * Whether this is a primary key column
     */
    isPrimary: boolean;
    /**
     * Whether this column can contain null values
     */
    isNullable: boolean;
    /**
     * Target table name for relation columns
     */
    relationTarget?: string;
    /**
     * Type of relation if this is a relation column
     */
    relationType?: 'one-to-one' | 'one-to-many' | 'many-to-one' | 'many-to-many';
    /**
     * Possible values for enum columns
     */
    enumValues?: Array<string>;
};

export type TableDataDto = {
    /**
     * Column metadata for the table
     */
    columns: Array<ColumnMetadataDto>;
    /**
     * Table rows data - each row is an array of values corresponding to columns
     */
    rows: Array<Array<string | number | boolean | {
        [key: string]: unknown;
    } | unknown>>;
    /**
     * Total number of records in the table (before pagination)
     */
    totalCount: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of records per page
     */
    limit: number;
    /**
     * Total number of pages
     */
    totalPages: number;
};

export type CreateRecordDto = {
    /**
     * Object containing column names and their values for the new record
     */
    record: {
        [key: string]: unknown;
    };
};

export type CreateRecordResponseDto = {
    /**
     * Whether the insert was successful
     */
    success: boolean;
    /**
     * Success or error message
     */
    message: string;
    /**
     * The created record data
     */
    createdRecord?: {
        [key: string]: unknown;
    };
};

export type UpdateRecordDto = {
    /**
     * The primary key value of the record to update
     */
    primaryKeyValue: {
        [key: string]: unknown;
    };
    /**
     * Object containing column names and their new values
     */
    updates: {
        [key: string]: unknown;
    };
};

export type UpdateRecordResponseDto = {
    /**
     * Whether the update was successful
     */
    success: boolean;
    /**
     * Success or error message
     */
    message: string;
    /**
     * The updated record data
     */
    updatedRecord?: {
        [key: string]: unknown;
    };
};

export type DeleteRecordsDto = {
    /**
     * Array of primary key values for records to delete
     */
    primaryKeyValues: Array<string>;
};

export type DeleteRecordsResponseDto = {
    /**
     * Whether the deletion was successful
     */
    success: boolean;
    /**
     * Descriptive message about the operation
     */
    message: string;
    /**
     * Number of records deleted
     */
    deletedCount: number;
    /**
     * Array of primary key values that were successfully deleted
     */
    deletedIds: Array<string>;
    /**
     * Array of primary key values that failed to delete
     */
    failedIds?: Array<string>;
};

export type SearchItemType = 'user' | 'action' | 'post' | 'recent' | 'other';

export type SearchItemDto = {
    id: string;
    name: string;
    date?: string;
    image?: string;
    webAppLocation: string;
    secondaryData?: Array<Array<unknown>>;
    type: SearchItemType;
};

export type SubmitFormDto = {
    answers: {
        [key: string]: unknown;
    };
    schemaSnapshot: {
        [key: string]: unknown;
    };
    actionId: number;
    visibilityValidatorResults?: {
        [key: string]: unknown;
    };
};

export type FormResponseDto = {
    id: number;
    formId: number;
    answers: {
        [key: string]: unknown;
    };
    visibilityValidatorResults: {
        [key: string]: unknown;
    };
    user: User;
    schemaSnapshot: {
        [key: string]: unknown;
    };
};

export type CreateFormDto = {
    title: string;
    schema: {
        [key: string]: unknown;
    };
};

export type FormDto = {
    id: number;
    title: string;
    schema: {
        [key: string]: unknown;
    };
    usedInAction?: ActionDto;
};

export type CustomValidatorType = 'UploadedPhoto' | 'SignedContract' | 'AddedProfileDescription' | 'RepliedToForumPost' | 'HasPhoneNumber';

export type CustomValidatorTypeDto = {
    name: string;
    id: CustomValidatorType;
    withIdField: boolean;
    usableForVisibility: boolean;
};

export type CustomValidatorResponseDto = {
    isValid: boolean;
    message?: string;
};

export type CustomValidatorDto = {
    id: number;
    type: CustomValidatorType;
    idArgument?: number;
};

export type CreateCustomValidatorDto = {
    type: CustomValidatorType;
    idArgument?: number;
};

export type CreateCustomValidatorResponseDto = {
    id: number;
};

export type TimeSpentForUserDto = {
    userId: number;
    timeSpent: number;
};

export type AppHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppHealthCheckResponses = {
    200: string;
};

export type AppHealthCheckResponse = AppHealthCheckResponses[keyof AppHealthCheckResponses];

export type AppTestErrorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test-error';
};

export type AppTestErrorResponses = {
    200: string;
};

export type AppTestErrorResponse = AppTestErrorResponses[keyof AppTestErrorResponses];

export type AuthLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    401: unknown;
};

export type AuthLoginResponses = {
    200: SignInResponseDto;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthAdminLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/admin/login';
};

export type AuthAdminLoginErrors = {
    401: unknown;
};

export type AuthAdminLoginResponses = {
    200: SignInResponseDto;
};

export type AuthAdminLoginResponse = AuthAdminLoginResponses[keyof AuthAdminLoginResponses];

export type AuthRegisterData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    401: unknown;
};

export type AuthRegisterResponses = {
    /**
     * User created successfully
     */
    201: SignInResponseDto;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshTokensResponses = {
    200: AccessToken;
};

export type AuthRefreshTokensResponse = AuthRefreshTokensResponses[keyof AuthRefreshTokensResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    200: UserDto;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    200: unknown;
};

export type AuthForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthForgotPasswordResponses = {
    200: unknown;
};

export type AuthResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthResetPasswordResponses = {
    200: unknown;
};

export type UserFindMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type UserFindMeErrors = {
    401: unknown;
};

export type UserFindMeResponses = {
    200: ProfileDto;
};

export type UserFindMeResponse = UserFindMeResponses[keyof UserFindMeResponses];

export type UserOnboardingData = {
    body: OnboardingDto;
    path?: never;
    query?: never;
    url: '/user/onboarding';
};

export type UserOnboardingErrors = {
    401: unknown;
};

export type UserOnboardingResponses = {
    200: unknown;
};

export type UserSignContractData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/signcontract';
};

export type UserSignContractErrors = {
    401: unknown;
};

export type UserSignContractResponses = {
    200: string;
};

export type UserSignContractResponse = UserSignContractResponses[keyof UserSignContractResponses];

export type UserSuspendContractData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/suspendcontract';
};

export type UserSuspendContractErrors = {
    401: unknown;
};

export type UserSuspendContractResponses = {
    200: string;
};

export type UserSuspendContractResponse = UserSuspendContractResponses[keyof UserSuspendContractResponses];

export type UserGetAwayRangesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/awayranges';
};

export type UserGetAwayRangesErrors = {
    401: unknown;
};

export type UserGetAwayRangesResponses = {
    200: Array<UserAwayRangeDto>;
};

export type UserGetAwayRangesResponse = UserGetAwayRangesResponses[keyof UserGetAwayRangesResponses];

export type UserCreateAwayRangeData = {
    body: CreateAwayRangeDto;
    path?: never;
    query?: never;
    url: '/user/awayranges';
};

export type UserCreateAwayRangeErrors = {
    401: unknown;
};

export type UserCreateAwayRangeResponses = {
    200: UserAwayRangeDto;
};

export type UserCreateAwayRangeResponse = UserCreateAwayRangeResponses[keyof UserCreateAwayRangeResponses];

export type UserDeleteAwayRangeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/awayranges/{id}';
};

export type UserDeleteAwayRangeErrors = {
    401: unknown;
};

export type UserDeleteAwayRangeResponses = {
    200: string;
};

export type UserDeleteAwayRangeResponse = UserDeleteAwayRangeResponses[keyof UserDeleteAwayRangeResponses];

export type UserUpdateData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/user/update';
};

export type UserUpdateResponses = {
    200: ProfileDto;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];

export type UserMyLocationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/mylocation';
};

export type UserMyLocationResponses = {
    200: City;
};

export type UserMyLocationResponse = UserMyLocationResponses[keyof UserMyLocationResponses];

export type UserRemoveFriendData = {
    body?: never;
    path: {
        targetUserId: number;
    };
    query?: never;
    url: '/user/friends/{targetUserId}';
};

export type UserRemoveFriendResponses = {
    /**
     * Relationship removed
     */
    200: unknown;
};

export type UserRequestFriendData = {
    body?: never;
    path: {
        targetUserId: number;
    };
    query?: never;
    url: '/user/friends/{targetUserId}';
};

export type UserRequestFriendResponses = {
    /**
     * Friend request is now pending
     */
    200: unknown;
};

export type UserAcceptFriendRequestData = {
    body?: never;
    path: {
        requesterId: number;
    };
    query?: never;
    url: '/user/friends/{requesterId}/accept';
};

export type UserAcceptFriendRequestResponses = {
    /**
     * Friend request accepted
     */
    200: unknown;
};

export type UserDeclineFriendRequestData = {
    body?: never;
    path: {
        requesterId: number;
    };
    query?: never;
    url: '/user/friends/{requesterId}/decline';
};

export type UserDeclineFriendRequestResponses = {
    /**
     * Friend request declined
     */
    200: unknown;
};

export type UserListReceivedRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/friends/requests/received';
};

export type UserListReceivedRequestsResponses = {
    200: Array<ProfileDto>;
};

export type UserListReceivedRequestsResponse = UserListReceivedRequestsResponses[keyof UserListReceivedRequestsResponses];

export type UserListSentRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/friends/requests/sent';
};

export type UserListSentRequestsResponses = {
    200: Array<ProfileDto>;
};

export type UserListSentRequestsResponse = UserListSentRequestsResponses[keyof UserListSentRequestsResponses];

export type UserMyFriendRelationshipData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/myfriendrelationship/{id}';
};

export type UserMyFriendRelationshipResponses = {
    200: FriendStatusDto;
};

export type UserMyFriendRelationshipResponse = UserMyFriendRelationshipResponses[keyof UserMyFriendRelationshipResponses];

export type UserPrefillData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/prefill/{id}';
};

export type UserPrefillErrors = {
    401: unknown;
};

export type UserPrefillResponses = {
    200: ProfileDto;
};

export type UserPrefillResponse = UserPrefillResponses[keyof UserPrefillResponses];

export type UserListFriendsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/listfriends/{id}';
};

export type UserListFriendsResponses = {
    200: Array<ProfileDto>;
};

export type UserListFriendsResponse = UserListFriendsResponses[keyof UserListFriendsResponses];

export type UserCountReferredData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/countreferred/{id}';
};

export type UserCountReferredResponses = {
    200: number;
};

export type UserCountReferredResponse = UserCountReferredResponses[keyof UserCountReferredResponses];

export type UserListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/list';
};

export type UserListResponses = {
    200: Array<User>;
};

export type UserListResponse = UserListResponses[keyof UserListResponses];

export type UserActionRelationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/action-relations';
};

export type UserActionRelationsResponses = {
    200: UserActionRelationsResponseDto;
};

export type UserActionRelationsResponse = UserActionRelationsResponses[keyof UserActionRelationsResponses];

export type UserMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/members';
};

export type UserMembersResponses = {
    200: Array<ProfileDto>;
};

export type UserMembersResponse = UserMembersResponses[keyof UserMembersResponses];

export type UserMembersWithFriendsData = {
    body?: never;
    path?: never;
    query: {
        requireSignedContract: boolean;
    };
    url: '/user/membersWithFriends';
};

export type UserMembersWithFriendsResponses = {
    200: Array<ProfileDtoWithFriends>;
};

export type UserMembersWithFriendsResponse = UserMembersWithFriendsResponses[keyof UserMembersWithFriendsResponses];

export type UserMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/myprofile';
};

export type UserMyProfileResponses = {
    200: ProfileDto;
};

export type UserMyProfileResponse = UserMyProfileResponses[keyof UserMyProfileResponses];

export type UserCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/count';
};

export type UserCountResponses = {
    200: number;
};

export type UserCountResponse = UserCountResponses[keyof UserCountResponses];

export type UserFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/slug/{id}';
};

export type UserFindOneErrors = {
    401: unknown;
};

export type UserFindOneResponses = {
    200: ProfileDto;
};

export type UserFindOneResponse = UserFindOneResponses[keyof UserFindOneResponses];

export type UserVerifyEmailData = {
    body: VerifyEmailBody;
    path?: never;
    query?: never;
    url: '/user/verifyEmail';
};

export type UserVerifyEmailResponses = {
    200: User;
};

export type UserVerifyEmailResponse = UserVerifyEmailResponses[keyof UserVerifyEmailResponses];

export type UserCreateGroupData = {
    body: CreateGroupDto;
    path?: never;
    query?: never;
    url: '/user/createGroup';
};

export type UserCreateGroupResponses = {
    200: GroupDto;
};

export type UserCreateGroupResponse = UserCreateGroupResponses[keyof UserCreateGroupResponses];

export type UserGetGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/groups';
};

export type UserGetGroupsResponses = {
    200: Array<GroupDto>;
};

export type UserGetGroupsResponse = UserGetGroupsResponses[keyof UserGetGroupsResponses];

export type UserAddUserToGroupData = {
    body: AddUserToGroupDto;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/user/groups/{groupId}/addUser';
};

export type UserAddUserToGroupResponses = {
    200: GroupDto;
};

export type UserAddUserToGroupResponse = UserAddUserToGroupResponses[keyof UserAddUserToGroupResponses];

export type UserRemoveUserFromGroupData = {
    body: AddUserToGroupDto;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/user/groups/{groupId}/removeUser';
};

export type UserRemoveUserFromGroupResponses = {
    200: GroupDto;
};

export type UserRemoveUserFromGroupResponse = UserRemoveUserFromGroupResponses[keyof UserRemoveUserFromGroupResponses];

export type UserUpdateGroupData = {
    body: CreateGroupDto;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/user/groups/{groupId}/update';
};

export type UserUpdateGroupResponses = {
    200: GroupDto;
};

export type UserUpdateGroupResponse = UserUpdateGroupResponses[keyof UserUpdateGroupResponses];

export type UserDeleteGroupData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/user/groups/{groupId}';
};

export type UserDeleteGroupResponses = {
    200: unknown;
};

export type UserReferrerProfileData = {
    body?: never;
    path: {
        code: string;
    };
    query?: never;
    url: '/user/referrerProfile/{code}';
};

export type UserReferrerProfileResponses = {
    200: ProfileDto;
};

export type UserReferrerProfileResponse = UserReferrerProfileResponses[keyof UserReferrerProfileResponses];

export type UserInviteeNameData = {
    body?: never;
    path: {
        code: string;
    };
    query?: never;
    url: '/user/inviteeName/{code}';
};

export type UserInviteeNameResponses = {
    200: string;
};

export type UserInviteeNameResponse = UserInviteeNameResponses[keyof UserInviteeNameResponses];

export type UserCreateOnetimeInviteData = {
    body: CreateOnetimeInviteDto;
    path?: never;
    query?: never;
    url: '/user/createOnetimeInvite';
};

export type UserCreateOnetimeInviteResponses = {
    200: OnetimeInviteDto;
};

export type UserCreateOnetimeInviteResponse = UserCreateOnetimeInviteResponses[keyof UserCreateOnetimeInviteResponses];

export type UserGetOnetimeInvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/onetimeInvites';
};

export type UserGetOnetimeInvitesResponses = {
    200: Array<OnetimeInviteDto>;
};

export type UserGetOnetimeInvitesResponse = UserGetOnetimeInvitesResponses[keyof UserGetOnetimeInvitesResponses];

export type ImagesGetImageData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/images/{key}';
};

export type ImagesGetImageResponses = {
    200: StreamableFile;
};

export type ImagesGetImageResponse = ImagesGetImageResponses[keyof ImagesGetImageResponses];

export type ImagesDeleteImageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/images/{id}';
};

export type ImagesDeleteImageResponses = {
    200: unknown;
};

export type ImagesUploadImageData = {
    body: {
        file?: string;
    };
    path?: never;
    query?: never;
    url: '/images/uploadImage';
};

export type ImagesUploadImageResponses = {
    200: UploadImageResponseDto;
};

export type ImagesUploadImageResponse = ImagesUploadImageResponses[keyof ImagesUploadImageResponses];

export type MailgunWebhookHandleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mailgun/handle-event';
};

export type MailgunWebhookHandleResponses = {
    200: unknown;
};

export type ActionsJoinData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/join/{id}';
};

export type ActionsJoinResponses = {
    200: ActionActivityDto;
};

export type ActionsJoinResponse = ActionsJoinResponses[keyof ActionsJoinResponses];

export type ActionsDeclineData = {
    body: DeclineActionDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/decline/{id}';
};

export type ActionsDeclineResponses = {
    200: ActionActivityDto;
};

export type ActionsDeclineResponse = ActionsDeclineResponses[keyof ActionsDeclineResponses];

export type ActionsOptoutData = {
    body: OptOutActionDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/optout/{id}';
};

export type ActionsOptoutResponses = {
    200: ActionActivityDto;
};

export type ActionsOptoutResponse = ActionsOptoutResponses[keyof ActionsOptoutResponses];

export type ActionsCompleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/complete/{id}';
};

export type ActionsCompleteResponses = {
    200: ActionActivityDto;
};

export type ActionsCompleteResponse = ActionsCompleteResponses[keyof ActionsCompleteResponses];

export type ActionsMyStatusData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/myStatus/{id}';
};

export type ActionsMyStatusResponses = {
    200: UserActionRelationDto;
};

export type ActionsMyStatusResponse = ActionsMyStatusResponses[keyof ActionsMyStatusResponses];

export type ActionsFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions';
};

export type ActionsFindAllResponses = {
    200: Array<ActionDto>;
};

export type ActionsFindAllResponse = ActionsFindAllResponses[keyof ActionsFindAllResponses];

export type ActionsFindAllLoggedInData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/loggedIn';
};

export type ActionsFindAllLoggedInResponses = {
    200: Array<ActionDto>;
};

export type ActionsFindAllLoggedInResponse = ActionsFindAllLoggedInResponses[keyof ActionsFindAllLoggedInResponses];

export type ActionsMyActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/myActivity';
};

export type ActionsMyActivityResponses = {
    200: Array<ActionActivityDto>;
};

export type ActionsMyActivityResponse = ActionsMyActivityResponses[keyof ActionsMyActivityResponses];

export type ActionsUserLocationsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/userlocations/{id}';
};

export type ActionsUserLocationsResponses = {
    200: Array<LatLonDto>;
};

export type ActionsUserLocationsResponse = ActionsUserLocationsResponses[keyof ActionsUserLocationsResponses];

export type ActionsGetActivityFeedData = {
    body?: never;
    path?: never;
    query: {
        limit: string;
        before: string;
    };
    url: '/actions/activities/feed';
};

export type ActionsGetActivityFeedResponses = {
    200: Array<ActionActivityDto>;
};

export type ActionsGetActivityFeedResponse = ActionsGetActivityFeedResponses[keyof ActionsGetActivityFeedResponses];

export type ActionsGetActivityData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/activities/{id}';
};

export type ActionsGetActivityResponses = {
    200: ActionActivityDto;
};

export type ActionsGetActivityResponse = ActionsGetActivityResponses[keyof ActionsGetActivityResponses];

export type ActionsGetEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/events/{id}';
};

export type ActionsGetEventResponses = {
    200: ActionEventDto;
};

export type ActionsGetEventResponse = ActionsGetEventResponses[keyof ActionsGetEventResponses];

export type ActionsGetNotificationScheduleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ISO timestamp for the start of the window
         */
        windowStart: string;
        /**
         * ISO timestamp for the end of the window
         */
        windowEnd: string;
    };
    url: '/actions/notification-schedule';
};

export type ActionsGetNotificationScheduleResponses = {
    200: Array<NotificationScheduleEntryDto>;
};

export type ActionsGetNotificationScheduleResponse = ActionsGetNotificationScheduleResponses[keyof ActionsGetNotificationScheduleResponses];

export type ActionsGetActionActivitiesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/{id}/activities';
};

export type ActionsGetActionActivitiesResponses = {
    200: Array<ActionActivityDto>;
};

export type ActionsGetActionActivitiesResponse = ActionsGetActionActivitiesResponses[keyof ActionsGetActionActivitiesResponses];

export type ActionsFindAllWithDraftsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/all';
};

export type ActionsFindAllWithDraftsResponses = {
    200: Array<ActionDto>;
};

export type ActionsFindAllWithDraftsResponse = ActionsFindAllWithDraftsResponses[keyof ActionsFindAllWithDraftsResponses];

export type ActionsSseActionCountData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/live/{id}';
};

export type ActionsSseActionCountResponses = {
    200: unknown;
};

export type ActionsLiveListData = {
    body?: never;
    path?: never;
    query: {
        ids: string;
    };
    url: '/actions/live-list';
};

export type ActionsLiveListResponses = {
    200: unknown;
};

export type ActionsFriendActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/friendActivity';
};

export type ActionsFriendActivityResponses = {
    200: Array<ActionActivityDto>;
};

export type ActionsFriendActivityResponse = ActionsFriendActivityResponses[keyof ActionsFriendActivityResponses];

export type ActionsFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/slug/{id}';
};

export type ActionsFindOneErrors = {
    401: unknown;
};

export type ActionsFindOneResponses = {
    200: ActionDto;
};

export type ActionsFindOneResponse = ActionsFindOneResponses[keyof ActionsFindOneResponses];

export type ActionsCreateData = {
    body: CreateActionDto;
    path?: never;
    query?: never;
    url: '/actions/create';
};

export type ActionsCreateResponses = {
    200: ActionDto;
};

export type ActionsCreateResponse = ActionsCreateResponses[keyof ActionsCreateResponses];

export type ActionsRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsRemoveResponses = {
    200: unknown;
};

export type ActionsUpdateData = {
    body: UpdateActionDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsUpdateResponses = {
    200: ActionDto;
};

export type ActionsUpdateResponse = ActionsUpdateResponses[keyof ActionsUpdateResponses];

export type ActionsFindCompletedForUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/completed/{id}';
};

export type ActionsFindCompletedForUserResponses = {
    200: Array<ActionActivityDto>;
};

export type ActionsFindCompletedForUserResponse = ActionsFindCompletedForUserResponses[keyof ActionsFindCompletedForUserResponses];

export type ActionsAddEventData = {
    body: CreateActionEventDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/{id}/events';
};

export type ActionsAddEventResponses = {
    200: ActionEvent;
};

export type ActionsAddEventResponse = ActionsAddEventResponses[keyof ActionsAddEventResponses];

export type ActionsUpdateReminderGroupData = {
    body: CreateTodReminderGroupDto;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/actions/remindergroups/{groupId}';
};

export type ActionsUpdateReminderGroupResponses = {
    200: ReminderGroup;
};

export type ActionsUpdateReminderGroupResponse = ActionsUpdateReminderGroupResponses[keyof ActionsUpdateReminderGroupResponses];

export type ActionsCreateReminderGroupData = {
    body: CreateTodReminderGroupDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/actions/events/{eventId}/createremindergroup';
};

export type ActionsCreateReminderGroupResponses = {
    200: ReminderGroup;
};

export type ActionsCreateReminderGroupResponse = ActionsCreateReminderGroupResponses[keyof ActionsCreateReminderGroupResponses];

export type ActionsDeleteReminderGroupData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/actions/reminders/{groupId}';
};

export type ActionsDeleteReminderGroupResponses = {
    200: unknown;
};

export type ActionsPlansForGroupData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/actions/plansForGroup/{groupId}';
};

export type ActionsPlansForGroupResponses = {
    200: Array<NotificationPlan>;
};

export type ActionsPlansForGroupResponse = ActionsPlansForGroupResponses[keyof ActionsPlansForGroupResponses];

export type ActionsSentNotifsForGroupData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/actions/sentNotifsForGroup/{groupId}';
};

export type ActionsSentNotifsForGroupResponses = {
    200: Array<ActionEventNotifDto>;
};

export type ActionsSentNotifsForGroupResponse = ActionsSentNotifsForGroupResponses[keyof ActionsSentNotifsForGroupResponses];

export type ActionsClearDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/clearDb';
};

export type ActionsClearDbResponses = {
    200: unknown;
};

export type ActionsSetTestRelationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/setTestRelations';
};

export type ActionsSetTestRelationsResponses = {
    200: unknown;
};

export type ActionsLikeActivityData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/likeActivity/{id}';
};

export type ActionsLikeActivityResponses = {
    200: ActionActivityDto;
};

export type ActionsLikeActivityResponse = ActionsLikeActivityResponses[keyof ActionsLikeActivityResponses];

export type ActionsUnlikeActivityData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/unlikeActivity/{id}';
};

export type ActionsUnlikeActivityResponses = {
    200: ActionActivityDto;
};

export type ActionsUnlikeActivityResponse = ActionsUnlikeActivityResponses[keyof ActionsUnlikeActivityResponses];

export type ActionsAddActivityCommentData = {
    body: CreateCommentDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/addActivityComment/{id}';
};

export type ActionsAddActivityCommentResponses = {
    200: CommentDto;
};

export type ActionsAddActivityCommentResponse = ActionsAddActivityCommentResponses[keyof ActionsAddActivityCommentResponses];

export type ActionsUpdateActivityData = {
    body: UpdateActionActivityDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/updateActivity/{id}';
};

export type ActionsUpdateActivityResponses = {
    200: ActionActivityDto;
};

export type ActionsUpdateActivityResponse = ActionsUpdateActivityResponses[keyof ActionsUpdateActivityResponses];

export type ActionsEventNotifDataData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        type: ActionStatus;
        sendNotifsTo: NotificationType;
    };
    url: '/actions/preEventNotifData/{id}';
};

export type ActionsEventNotifDataResponses = {
    200: PreEventNotifDataDto;
};

export type ActionsEventNotifDataResponse = ActionsEventNotifDataResponses[keyof ActionsEventNotifDataResponses];

export type ActionsCreateActivityData = {
    body: CreateActionActivityDto;
    path?: never;
    query?: never;
    url: '/actions/createActivity';
};

export type ActionsCreateActivityResponses = {
    200: ActionActivityDto;
};

export type ActionsCreateActivityResponse = ActionsCreateActivityResponses[keyof ActionsCreateActivityResponses];

export type ActionsArchiveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/archive/{id}';
};

export type ActionsArchiveResponses = {
    200: ActionDto;
};

export type ActionsArchiveResponse = ActionsArchiveResponses[keyof ActionsArchiveResponses];

export type ActionsUnarchiveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/unarchive/{id}';
};

export type ActionsUnarchiveResponses = {
    200: ActionDto;
};

export type ActionsUnarchiveResponse = ActionsUnarchiveResponses[keyof ActionsUnarchiveResponses];

export type ActionsReminderGroupsForEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/reminderGroupsForEvent/{id}';
};

export type ActionsReminderGroupsForEventResponses = {
    200: Array<ReminderGroup>;
};

export type ActionsReminderGroupsForEventResponse = ActionsReminderGroupsForEventResponses[keyof ActionsReminderGroupsForEventResponses];

export type ActionsCreateUpdateData = {
    body: CreateActionUpdateDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/createUpdate/{id}';
};

export type ActionsCreateUpdateResponses = {
    200: ActionUpdate;
};

export type ActionsCreateUpdateResponse = ActionsCreateUpdateResponses[keyof ActionsCreateUpdateResponses];

export type ActionsSuitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions/suites';
};

export type ActionsSuitesResponses = {
    200: Array<ActionSuite>;
};

export type ActionsSuitesResponse = ActionsSuitesResponses[keyof ActionsSuitesResponses];

export type ActionsSuiteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/actions/suite/{id}';
};

export type ActionsSuiteResponses = {
    200: ActionSuiteDto;
};

export type ActionsSuiteResponse = ActionsSuiteResponses[keyof ActionsSuiteResponses];

export type ActionsCreateSuiteData = {
    body: CreateActionSuiteDto;
    path?: never;
    query?: never;
    url: '/actions/createSuite';
};

export type ActionsCreateSuiteResponses = {
    200: ActionSuiteDto;
};

export type ActionsCreateSuiteResponse = ActionsCreateSuiteResponses[keyof ActionsCreateSuiteResponses];

export type ActionsBatchUpdateSuiteEventsData = {
    body: UpdateActionEventDto;
    path: {
        suiteId: number;
        eventId: number;
    };
    query?: never;
    url: '/actions/suite/{suiteId}/batchUpdateSuiteEvents/{eventId}';
};

export type ActionsBatchUpdateSuiteEventsResponses = {
    200: unknown;
};

export type ActionsAddSuiteEventData = {
    body: CreateActionEventDto;
    path: {
        suiteId: number;
    };
    query?: never;
    url: '/actions/suite/{suiteId}/events';
};

export type ActionsAddSuiteEventResponses = {
    200: ActionSuiteDto;
};

export type ActionsAddSuiteEventResponse = ActionsAddSuiteEventResponses[keyof ActionsAddSuiteEventResponses];

export type ActionsDeleteSuiteEventData = {
    body?: never;
    path: {
        suiteId: number;
        eventId: number;
    };
    query?: never;
    url: '/actions/suite/{suiteId}/events/{eventId}';
};

export type ActionsDeleteSuiteEventResponses = {
    200: ActionSuiteDto;
};

export type ActionsDeleteSuiteEventResponse = ActionsDeleteSuiteEventResponses[keyof ActionsDeleteSuiteEventResponses];

export type ActionsTentativePlansForGroupData = {
    body: CreateTodReminderGroupDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/actions/events/{eventId}/checkTentativePlans';
};

export type ActionsTentativePlansForGroupResponses = {
    200: Array<NotificationPlan>;
};

export type ActionsTentativePlansForGroupResponse = ActionsTentativePlansForGroupResponses[keyof ActionsTentativePlansForGroupResponses];

export type NotifsFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifs';
};

export type NotifsFindAllResponses = {
    200: Array<NotificationDto>;
};

export type NotifsFindAllResponse = NotifsFindAllResponses[keyof NotifsFindAllResponses];

export type NotifsSetReadData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/notifs/read/{id}';
};

export type NotifsSetReadResponses = {
    200: unknown;
};

export type NotifsSetReadAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifs/read-all';
};

export type NotifsSetReadAllResponses = {
    200: unknown;
};

export type NotifsClearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifs/clear';
};

export type NotifsClearResponses = {
    200: unknown;
};

export type NotifsNotifsForUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/notifs/for-user/{id}';
};

export type NotifsNotifsForUserResponses = {
    200: Array<ActionEventNotifDto>;
};

export type NotifsNotifsForUserResponse = NotifsNotifsForUserResponses[keyof NotifsNotifsForUserResponses];

export type NotifsLinkClickData = {
    body: NotifClickDto;
    path?: never;
    query?: never;
    url: '/notifs/linkClick';
};

export type NotifsLinkClickResponses = {
    200: NotifClickResponseDto;
};

export type NotifsLinkClickResponse = NotifsLinkClickResponses[keyof NotifsLinkClickResponses];

export type ForumFindAllPostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/forum/posts';
};

export type ForumFindAllPostsResponses = {
    200: Array<PostDto>;
};

export type ForumFindAllPostsResponse = ForumFindAllPostsResponses[keyof ForumFindAllPostsResponses];

export type ForumCreatePostData = {
    body: CreatePostDto;
    path?: never;
    query?: never;
    url: '/forum/posts';
};

export type ForumCreatePostResponses = {
    200: PostDto;
};

export type ForumCreatePostResponse = ForumCreatePostResponses[keyof ForumCreatePostResponses];

export type ForumFindPostsByActionData = {
    body?: never;
    path: {
        actionId: string;
    };
    query?: never;
    url: '/forum/posts/action/{actionId}';
};

export type ForumFindPostsByActionResponses = {
    200: Array<PostDto>;
};

export type ForumFindPostsByActionResponse = ForumFindPostsByActionResponses[keyof ForumFindPostsByActionResponses];

export type ForumRemovePostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type ForumRemovePostResponses = {
    200: unknown;
};

export type ForumFindOnePostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type ForumFindOnePostResponses = {
    200: PostDto;
};

export type ForumFindOnePostResponse = ForumFindOnePostResponses[keyof ForumFindOnePostResponses];

export type ForumUpdatePostData = {
    body: UpdatePostDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type ForumUpdatePostResponses = {
    200: PostDto;
};

export type ForumUpdatePostResponse = ForumUpdatePostResponses[keyof ForumUpdatePostResponses];

export type ForumFindCommentsForPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}/comments';
};

export type ForumFindCommentsForPostResponses = {
    200: Array<CommentDto>;
};

export type ForumFindCommentsForPostResponse = ForumFindCommentsForPostResponses[keyof ForumFindCommentsForPostResponses];

export type ForumFindCommentsForActivityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/forum/activity/{id}/comments';
};

export type ForumFindCommentsForActivityResponses = {
    200: Array<CommentDto>;
};

export type ForumFindCommentsForActivityResponse = ForumFindCommentsForActivityResponses[keyof ForumFindCommentsForActivityResponses];

export type ForumFindCommentsForActionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/forum/actions/{id}/comments';
};

export type ForumFindCommentsForActionResponses = {
    200: Array<CommentDto>;
};

export type ForumFindCommentsForActionResponse = ForumFindCommentsForActionResponses[keyof ForumFindCommentsForActionResponses];

export type ForumFindPostsByUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/user/{id}';
};

export type ForumFindPostsByUserResponses = {
    200: Array<PostDto>;
};

export type ForumFindPostsByUserResponse = ForumFindPostsByUserResponses[keyof ForumFindPostsByUserResponses];

export type ForumFindCommentsByUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/user/{id}/comments';
};

export type ForumFindCommentsByUserResponses = {
    200: Array<UserCommentDto>;
};

export type ForumFindCommentsByUserResponse = ForumFindCommentsByUserResponses[keyof ForumFindCommentsByUserResponses];

export type ForumFindForumCommentsByUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/user/{id}/forumComments';
};

export type ForumFindForumCommentsByUserResponses = {
    200: Array<CommentDto>;
};

export type ForumFindForumCommentsByUserResponse = ForumFindForumCommentsByUserResponses[keyof ForumFindForumCommentsByUserResponses];

export type ForumCreateCommentData = {
    body: CreateCommentDto;
    path?: never;
    query?: never;
    url: '/forum/comments';
};

export type ForumCreateCommentResponses = {
    200: CommentDto;
};

export type ForumCreateCommentResponse = ForumCreateCommentResponses[keyof ForumCreateCommentResponses];

export type ForumDeleteCommentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/comments/{id}';
};

export type ForumDeleteCommentResponses = {
    200: unknown;
};

export type ForumUpdateCommentData = {
    body: UpdateCommentDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/comments/{id}';
};

export type ForumUpdateCommentResponses = {
    200: CommentDto;
};

export type ForumUpdateCommentResponse = ForumUpdateCommentResponses[keyof ForumUpdateCommentResponses];

export type ForumLikeCommentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/comments/{id}/like';
};

export type ForumLikeCommentResponses = {
    200: CommentDto;
};

export type ForumLikeCommentResponse = ForumLikeCommentResponses[keyof ForumLikeCommentResponses];

export type ForumUnlikeCommentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/comments/{id}/unlike';
};

export type ForumUnlikeCommentResponses = {
    200: CommentDto;
};

export type ForumUnlikeCommentResponse = ForumUnlikeCommentResponses[keyof ForumUnlikeCommentResponses];

export type ForumLikePostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/{id}/like';
};

export type ForumLikePostResponses = {
    200: PostDto;
};

export type ForumLikePostResponse = ForumLikePostResponses[keyof ForumLikePostResponses];

export type ForumUnlikePostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/forum/posts/{id}/unlike';
};

export type ForumUnlikePostResponses = {
    200: PostDto;
};

export type ForumUnlikePostResponse = ForumUnlikePostResponses[keyof ForumUnlikePostResponses];

export type GeoSearchCityData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        latitude?: number;
        longitude?: number;
    };
    url: '/geo/search-city';
};

export type GeoSearchCityResponses = {
    default: Array<CitySearchDto>;
};

export type GeoSearchCityResponse = GeoSearchCityResponses[keyof GeoSearchCityResponses];

export type GeoLoadCountryDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/geo/load-country-data';
};

export type GeoLoadCountryDataResponses = {
    200: Array<City>;
};

export type GeoLoadCountryDataResponse = GeoLoadCountryDataResponses[keyof GeoLoadCountryDataResponses];

export type GeoLoadCityDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/geo/ip';
};

export type GeoLoadCityDataResponses = {
    200: unknown;
};

export type PaymentsCreatePaymentIntentData = {
    body: CreatePaymentIntentDto;
    path?: never;
    query?: never;
    url: '/payments/create-payment-intent';
};

export type PaymentsCreatePaymentIntentResponses = {
    200: ClientSecretDto;
};

export type PaymentsCreatePaymentIntentResponse = PaymentsCreatePaymentIntentResponses[keyof PaymentsCreatePaymentIntentResponses];

export type PaymentsSetPartialProfileData = {
    body: CreatePartialProfileDto;
    path?: never;
    query?: never;
    url: '/payments/set-partial-profile';
};

export type PaymentsSetPartialProfileResponses = {
    200: unknown;
};

export type PaymentsWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payments/webhook';
};

export type PaymentsWebhookResponses = {
    200: unknown;
};

export type PaymentsPaymentMethodData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payments/payment-method';
};

export type PaymentsPaymentMethodResponses = {
    200: PaymentMethodDto;
};

export type PaymentsPaymentMethodResponse = PaymentsPaymentMethodResponses[keyof PaymentsPaymentMethodResponses];

export type PaymentsClearPaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payments/clear-payment-method';
};

export type PaymentsClearPaymentMethodsResponses = {
    200: unknown;
};

export type AdminViewerGetTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin-viewer/tables';
};

export type AdminViewerGetTablesResponses = {
    200: TableListDto;
};

export type AdminViewerGetTablesResponse = AdminViewerGetTablesResponses[keyof AdminViewerGetTablesResponses];

export type AdminViewerGetTableDataData = {
    body?: never;
    path: {
        /**
         * Name of the database table
         */
        tableName: string;
    };
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of records per page
         */
        limit?: number;
        /**
         * Column name to sort by
         */
        sortBy?: string;
        /**
         * Sort order
         */
        sortOrder?: 'ASC' | 'DESC';
        /**
         * Search term to filter results
         */
        search?: string;
    };
    url: '/admin-viewer/tables/{tableName}/data';
};

export type AdminViewerGetTableDataErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
    /**
     * Table not found
     */
    404: unknown;
};

export type AdminViewerGetTableDataResponses = {
    200: TableDataDto;
};

export type AdminViewerGetTableDataResponse = AdminViewerGetTableDataResponses[keyof AdminViewerGetTableDataResponses];

export type AdminViewerDeleteRecordsData = {
    body: DeleteRecordsDto;
    path: {
        /**
         * Name of the database table
         */
        tableName: string;
    };
    query?: never;
    url: '/admin-viewer/tables/{tableName}/records';
};

export type AdminViewerDeleteRecordsErrors = {
    /**
     * Invalid delete data or validation failed
     */
    400: unknown;
    /**
     * Table not found
     */
    404: unknown;
};

export type AdminViewerDeleteRecordsResponses = {
    200: DeleteRecordsResponseDto;
};

export type AdminViewerDeleteRecordsResponse = AdminViewerDeleteRecordsResponses[keyof AdminViewerDeleteRecordsResponses];

export type AdminViewerCreateRecordData = {
    body: CreateRecordDto;
    path: {
        /**
         * Name of the database table
         */
        tableName: string;
    };
    query?: never;
    url: '/admin-viewer/tables/{tableName}/records';
};

export type AdminViewerCreateRecordErrors = {
    /**
     * Invalid create data or validation failed
     */
    400: unknown;
    /**
     * Table not found
     */
    404: unknown;
};

export type AdminViewerCreateRecordResponses = {
    200: CreateRecordResponseDto;
};

export type AdminViewerCreateRecordResponse = AdminViewerCreateRecordResponses[keyof AdminViewerCreateRecordResponses];

export type AdminViewerUpdateRecordData = {
    body: UpdateRecordDto;
    path: {
        /**
         * Name of the database table
         */
        tableName: string;
    };
    query?: never;
    url: '/admin-viewer/tables/{tableName}/records';
};

export type AdminViewerUpdateRecordErrors = {
    /**
     * Invalid update data or validation failed
     */
    400: unknown;
    /**
     * Table or record not found
     */
    404: unknown;
};

export type AdminViewerUpdateRecordResponses = {
    200: UpdateRecordResponseDto;
};

export type AdminViewerUpdateRecordResponse = AdminViewerUpdateRecordResponses[keyof AdminViewerUpdateRecordResponses];

export type SearchAllData = {
    body?: never;
    path?: never;
    query: {
        query: string;
    };
    url: '/search/all';
};

export type SearchAllResponses = {
    200: Array<SearchItemDto>;
};

export type SearchAllResponse = SearchAllResponses[keyof SearchAllResponses];

export type SearchSaveSelectedData = {
    body: SearchItemDto;
    path?: never;
    query?: never;
    url: '/search/selected';
};

export type SearchSaveSelectedResponses = {
    200: unknown;
};

export type TasksSubmitFormData = {
    body: SubmitFormDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/submitForm/{id}';
};

export type TasksSubmitFormResponses = {
    200: FormResponseDto;
};

export type TasksSubmitFormResponse = TasksSubmitFormResponses[keyof TasksSubmitFormResponses];

export type TasksCreateFormData = {
    body: CreateFormDto;
    path?: never;
    query?: never;
    url: '/tasks/createForm';
};

export type TasksCreateFormResponses = {
    200: FormDto;
};

export type TasksCreateFormResponse = TasksCreateFormResponses[keyof TasksCreateFormResponses];

export type TasksListFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/listForms';
};

export type TasksListFormsResponses = {
    200: Array<FormDto>;
};

export type TasksListFormsResponse = TasksListFormsResponses[keyof TasksListFormsResponses];

export type TasksGetFormResponsesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/responses/{id}';
};

export type TasksGetFormResponsesResponses = {
    200: Array<FormResponseDto>;
};

export type TasksGetFormResponsesResponse = TasksGetFormResponsesResponses[keyof TasksGetFormResponsesResponses];

export type TasksGetMyFormResponseData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/myResponse/{id}';
};

export type TasksGetMyFormResponseResponses = {
    200: FormResponseDto;
};

export type TasksGetMyFormResponseResponse = TasksGetMyFormResponseResponses[keyof TasksGetMyFormResponseResponses];

export type TasksGetFormData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/slug/{id}';
};

export type TasksGetFormResponses = {
    200: FormDto;
};

export type TasksGetFormResponse = TasksGetFormResponses[keyof TasksGetFormResponses];

export type TasksUpdateFormData = {
    body: CreateFormDto;
    path: {
        formId: number;
    };
    query?: never;
    url: '/tasks/updateForm/{formId}';
};

export type TasksUpdateFormResponses = {
    200: FormDto;
};

export type TasksUpdateFormResponse = TasksUpdateFormResponses[keyof TasksUpdateFormResponses];

export type TasksDeleteFormData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TasksDeleteFormResponses = {
    200: unknown;
};

export type TasksCustomValidatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/customValidators';
};

export type TasksCustomValidatorsResponses = {
    200: Array<CustomValidatorTypeDto>;
};

export type TasksCustomValidatorsResponse = TasksCustomValidatorsResponses[keyof TasksCustomValidatorsResponses];

export type TasksRunValidatorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/runValidator/{id}';
};

export type TasksRunValidatorResponses = {
    200: CustomValidatorResponseDto;
};

export type TasksRunValidatorResponse = TasksRunValidatorResponses[keyof TasksRunValidatorResponses];

export type TasksFindOneCustomValidatorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/findOneCustomValidator/{id}';
};

export type TasksFindOneCustomValidatorResponses = {
    200: CustomValidatorDto;
};

export type TasksFindOneCustomValidatorResponse = TasksFindOneCustomValidatorResponses[keyof TasksFindOneCustomValidatorResponses];

export type TasksCreateCustomValidatorData = {
    body: CreateCustomValidatorDto;
    path?: never;
    query?: never;
    url: '/tasks/createCustomValidator';
};

export type TasksCreateCustomValidatorResponses = {
    200: CreateCustomValidatorResponseDto;
};

export type TasksCreateCustomValidatorResponse = TasksCreateCustomValidatorResponses[keyof TasksCreateCustomValidatorResponses];

export type AnalyticsGetTimeSpentPerUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics/time-spent-per-user';
};

export type AnalyticsGetTimeSpentPerUserResponses = {
    200: Array<TimeSpentForUserDto>;
};

export type AnalyticsGetTimeSpentPerUserResponse = AnalyticsGetTimeSpentPerUserResponses[keyof AnalyticsGetTimeSpentPerUserResponses];

export type AnalyticsGetTimeSpentPerUserTotalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/analytics/time-spent-per-user-total';
};

export type AnalyticsGetTimeSpentPerUserTotalResponses = {
    200: Array<TimeSpentForUserDto>;
};

export type AnalyticsGetTimeSpentPerUserTotalResponse = AnalyticsGetTimeSpentPerUserTotalResponses[keyof AnalyticsGetTimeSpentPerUserTotalResponses];

export type ClientOptions = {
    baseUrl: string;
};