// This file is auto-generated by @hey-api/openapi-ts

export type SignInDto = {
    email: string;
    password: string;
};

export type AuthTokens = {
    access_token: string;
    refresh_token: string;
};

export type SignUp = {
    name: string;
    email: string;
    password: string;
};

export type AccessToken = {
    access_token: string;
};

export type ProfileDto = {
    email: string;
    name: string;
};

export type ActionDto = {
    name: string;
    category: string;
    whyJoin: string;
    type: string;
    description: string;
    status: 'Active' | 'Upcoming' | 'Past' | 'Draft';
};

export type AllActionsDto = {
    actions: Array<string>;
};

export type UpdateActionDto = {
    [key: string]: unknown;
};

export type AppHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppHealthCheckResponses = {
    200: unknown;
};

export type AuthLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    401: unknown;
};

export type AuthLoginResponses = {
    200: AuthTokens;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthAdminLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/admin/login';
};

export type AuthAdminLoginErrors = {
    401: unknown;
};

export type AuthAdminLoginResponses = {
    200: AuthTokens;
};

export type AuthAdminLoginResponse = AuthAdminLoginResponses[keyof AuthAdminLoginResponses];

export type AuthRegisterData = {
    body: SignUp;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    401: unknown;
};

export type AuthRegisterResponses = {
    /**
     * User created successfully
     */
    201: unknown;
};

export type AuthRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshTokensResponses = {
    200: AccessToken;
};

export type AuthRefreshTokensResponse = AuthRefreshTokensResponses[keyof AuthRefreshTokensResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    200: ProfileDto;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type ActionsCreateData = {
    body: ActionDto;
    path?: never;
    query?: never;
    url: '/actions/create';
};

export type ActionsCreateResponses = {
    201: unknown;
};

export type ActionsRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsRemoveResponses = {
    200: unknown;
};

export type ActionsFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsFindOneErrors = {
    401: unknown;
};

export type ActionsFindOneResponses = {
    200: ActionDto;
};

export type ActionsFindOneResponse = ActionsFindOneResponses[keyof ActionsFindOneResponses];

export type ActionsUpdateData = {
    body: UpdateActionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsUpdateResponses = {
    200: unknown;
};

export type ActionsJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsJoinResponses = {
    201: unknown;
};

export type ActionsFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions';
};

export type ActionsFindAllResponses = {
    200: Array<AllActionsDto>;
};

export type ActionsFindAllResponse = ActionsFindAllResponses[keyof ActionsFindAllResponses];

export type ClientOptions = {
    baseUrl: string;
};