import type { AdminActionListItemDto } from "@alliance/shared/client";

export const adminActionListItem = (
  id: number,
  name: string,
  overrides: Partial<AdminActionListItemDto> = {},
): AdminActionListItemDto => ({
  id,
  name,
  category: [],
  body: "",
  shortDescription: "",
  createdAt: "2026-01-02T00:00:00.000Z",
  updatedAt: "2026-01-02T00:00:00.000Z",
  isContractSigningAction: false,
  visibilityMode: "all_members",
  usersJoined: 0,
  onboarding: false,
  archived: false,
  priority: 0,
  optional: false,
  preventCompletion: false,
  publicOnly: false,
  shouldCompleteAfterDeadline: false,
  isForumParticipationAction: false,
  reviewers: [],
  followUpForms: [],
  usersCompleted: 0,
  events: [],
  status: "draft",
  updates: [],
  staffPreview: false,
  prerequisiteActionIds: [],
  variantFormIds: [],
  memberActionStart: null,
  memberActionDeadline: null,
  ...overrides,
});
