import { CreateReminderGroupDto } from "@alliance/shared/client";
import {
  defaultAnnouncementEmailContents,
  defaultAnnouncementEmailSubject,
  defaultAnnouncementPushMessage,
  defaultAnnouncementTextMessage,
  defaultEmailContents,
  defaultEmailSubject,
  defaultGroupLeadsEmailContents,
  defaultGroupLeadsEmailSubject,
  defaultGroupLeadsTextMessage,
  defaultMissedDeadlineEmailContents,
  defaultMissedDeadlineEmailSubject,
  defaultMissedDeadlineTextMessage,
  defaultPushMessage,
  defaultTextMessage,
} from "./defaultReminderContents";

export const presetNames = [
  "Announcement",
  "Catch-up late joiners",
  "Two Day Range",
  "One Day Range",
  "Three Hour",
  "Missed Deadline",
  "Group Leads 3 days",
  "Group Leads 2 days",
] as const;

export type ReminderPresetName = (typeof presetNames)[number];

/**
 * `anchorToDependencyDeadline` is a UI-only marker: the reminders tab resolves
 * it to a concrete `timingAnchorEventId` (the next upcoming dependency
 * deadline event) before the preset reaches the form/API.
 */
export type ReminderPreset = Omit<CreateReminderGroupDto, "suiteId"> & {
  anchorToDependencyDeadline?: boolean;
};

export const reminderPresets: Record<ReminderPresetName, ReminderPreset> = {
  Announcement: {
    timingMode: "event_launch",
    cohortType: "all_uncompleted",
    textMessage: defaultAnnouncementTextMessage,
    name: "Member Action announcement",
    emailMessage: defaultAnnouncementEmailContents,
    emailSubject: defaultAnnouncementEmailSubject,
    pushMessage: defaultAnnouncementPushMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: false,
    excludePreviouslyNotified: false,
  },
  "Catch-up late joiners": {
    timingMode: "from_deadline",
    sendAtSecondsFromDeadline: 0,
    anchorToDependencyDeadline: true,
    cohortType: "all_uncompleted",
    textMessage: defaultAnnouncementTextMessage,
    name: "Catch-up announcement for late cohort joiners",
    emailMessage: defaultAnnouncementEmailContents,
    emailSubject: defaultAnnouncementEmailSubject,
    pushMessage: defaultAnnouncementPushMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: false,
    excludePreviouslyNotified: true,
  },
  "Two Day Range": {
    timingMode: "within_relative_range",
    relative_range_start_seconds_from_deadline: 48 * 60 * 60,
    relative_range_end_seconds_from_deadline: 24 * 60 * 60,
    cohortType: "all_uncompleted",
    textMessage: defaultTextMessage,
    emailSubject: defaultEmailSubject,
    emailMessage: defaultEmailContents,
    name: "24-48h reminder",
    pushMessage: defaultPushMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: false,
    excludePreviouslyNotified: false,
  },
  "One Day Range": {
    timingMode: "within_relative_range",
    relative_range_start_seconds_from_deadline: 24 * 60 * 60,
    relative_range_end_seconds_from_deadline: 6 * 60 * 60,
    cohortType: "all_uncompleted",
    textMessage: defaultTextMessage,
    emailSubject: defaultEmailSubject,
    emailMessage: defaultEmailContents,
    name: "6-24h reminder",
    pushMessage: defaultPushMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: false,
    excludePreviouslyNotified: false,
  },
  "Three Hour": {
    timingMode: "from_deadline",
    sendAtSecondsFromDeadline: 3 * 60 * 60,
    cohortType: "all_uncompleted",
    textMessage: defaultTextMessage,
    emailSubject: defaultEmailSubject,
    emailMessage: defaultEmailContents,
    name: "3 hour reminder",
    pushMessage: defaultPushMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: false,
    excludePreviouslyNotified: false,
  },
  "Missed Deadline": {
    timingMode: "from_deadline",
    sendAtSecondsFromDeadline: 0,
    cohortType: "all_uncompleted",
    textMessage: defaultMissedDeadlineTextMessage,
    emailMessage: defaultMissedDeadlineEmailContents,
    emailSubject: defaultMissedDeadlineEmailSubject,
    name: "Missed deadline message",
    pushMessage: defaultMissedDeadlineTextMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: true,
    excludePreviouslyNotified: false,
  },
  "Group Leads 3 days": {
    timingMode: "within_relative_range",
    relative_range_start_seconds_from_deadline: 3 * 24 * 60 * 60,
    relative_range_end_seconds_from_deadline: 2 * 24 * 60 * 60,
    cohortType: "group_leads_with_uncompleted",
    textMessage: defaultGroupLeadsTextMessage,
    emailSubject: defaultGroupLeadsEmailSubject,
    emailMessage: defaultGroupLeadsEmailContents,
    name: "Group leads 3 days reminder",
    pushMessage: defaultGroupLeadsTextMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: true,
    excludePreviouslyNotified: false,
  },
  "Group Leads 2 days": {
    timingMode: "within_relative_range",
    relative_range_start_seconds_from_deadline: 2 * 24 * 60 * 60,
    relative_range_end_seconds_from_deadline: 1 * 24 * 60 * 60,
    cohortType: "group_leads_with_uncompleted",
    textMessage: defaultGroupLeadsTextMessage,
    emailSubject: defaultGroupLeadsEmailSubject,
    emailMessage: defaultGroupLeadsEmailContents,
    name: "Group leads 2 days reminder",
    pushMessage: defaultGroupLeadsTextMessage,
    useSuiteTaskCount: true,
    excludeOptionalActions: true,
    excludePreviouslyNotified: false,
  },
};
