/** Generates country names because Hermes lacks `Intl.DisplayNames`. */
import { getCountries } from "libphonenumber-js/max";

const names = new Intl.DisplayNames(["en"], { type: "region" });

const entries = getCountries()
  .slice()
  .sort()
  .map((country) => {
    const name = names.of(country);
    if (!name || name === country) {
      throw new Error(`no English region name for ${country}`);
    }
    return `  ${country}: ${JSON.stringify(name)},`;
  });

process.stdout.write(
  `// Generated by scripts/generate-country-names.ts — do not edit by hand.
import type { CountryCode } from "libphonenumber-js/max";

/** English country names for Hermes. */
export const COUNTRY_NAMES: Record<CountryCode, string> = {
${entries.join("\n")}
};
`,
);
