// This file is auto-generated by @hey-api/openapi-ts

export type SignInDto = {
    email: string;
    password: string;
};

export type AuthTokens = {
    access_token: string;
    refresh_token: string;
};

export type SignUp = {
    name: string;
    email: string;
    password: string;
};

export type AccessToken = {
    access_token: string;
};

export type ProfileDto = {
    email: string;
    name: string;
};

export type CreateActionDto = {
    name: string;
    image: string;
    category: string;
    whyJoin: string;
    type: string;
    description: string;
    status: 'Active' | 'Upcoming' | 'Past' | 'Draft';
};

export type ActionDto = {
    id: number;
    name: string;
    image: string;
    category: string;
    whyJoin: string;
    type: string;
    description: string;
    status: 'Active' | 'Upcoming' | 'Past' | 'Draft';
};

export type UpdateActionDto = {
    [key: string]: unknown;
};

export type CreateCommuniqueDto = {
    title: string;
    description: string;
    image: string;
};

export type UpdateCommuniqueDto = {
    title?: string;
    description?: string;
    image?: string;
};

export type ImageResponseDto = {
    /**
     * The filename of the image
     */
    filename: string;
};

export type AppHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppHealthCheckResponses = {
    200: unknown;
};

export type AuthLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    401: unknown;
};

export type AuthLoginResponses = {
    200: AuthTokens;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthAdminLoginData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/admin/login';
};

export type AuthAdminLoginErrors = {
    401: unknown;
};

export type AuthAdminLoginResponses = {
    200: AuthTokens;
};

export type AuthAdminLoginResponse = AuthAdminLoginResponses[keyof AuthAdminLoginResponses];

export type AuthRegisterData = {
    body: SignUp;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    401: unknown;
};

export type AuthRegisterResponses = {
    /**
     * User created successfully
     */
    201: unknown;
};

export type AuthRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshTokensResponses = {
    200: AccessToken;
};

export type AuthRefreshTokensResponse = AuthRefreshTokensResponses[keyof AuthRefreshTokensResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    200: ProfileDto;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type ActionsCreateData = {
    body: CreateActionDto;
    path?: never;
    query?: never;
    url: '/actions/create';
};

export type ActionsCreateResponses = {
    201: unknown;
};

export type ActionsRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsRemoveResponses = {
    200: unknown;
};

export type ActionsFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsFindOneErrors = {
    401: unknown;
};

export type ActionsFindOneResponses = {
    200: ActionDto;
};

export type ActionsFindOneResponse = ActionsFindOneResponses[keyof ActionsFindOneResponses];

export type ActionsUpdateData = {
    body: UpdateActionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsUpdateResponses = {
    200: unknown;
};

export type ActionsJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type ActionsJoinResponses = {
    201: unknown;
};

export type ActionsFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions';
};

export type ActionsFindAllResponses = {
    200: Array<ActionDto>;
};

export type ActionsFindAllResponse = ActionsFindAllResponses[keyof ActionsFindAllResponses];

export type CommuniquesFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/communiques';
};

export type CommuniquesFindAllResponses = {
    200: Array<CreateCommuniqueDto>;
};

export type CommuniquesFindAllResponse = CommuniquesFindAllResponses[keyof CommuniquesFindAllResponses];

export type CommuniquesCreateData = {
    body: CreateCommuniqueDto;
    path?: never;
    query?: never;
    url: '/communiques';
};

export type CommuniquesCreateResponses = {
    201: CreateCommuniqueDto;
};

export type CommuniquesCreateResponse = CommuniquesCreateResponses[keyof CommuniquesCreateResponses];

export type CommuniquesRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communiques/{id}';
};

export type CommuniquesRemoveResponses = {
    200: boolean;
};

export type CommuniquesRemoveResponse = CommuniquesRemoveResponses[keyof CommuniquesRemoveResponses];

export type CommuniquesFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/communiques/{id}';
};

export type CommuniquesFindOneResponses = {
    200: CreateCommuniqueDto;
};

export type CommuniquesFindOneResponse = CommuniquesFindOneResponses[keyof CommuniquesFindOneResponses];

export type CommuniquesUpdateData = {
    body: UpdateCommuniqueDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/communiques/{id}';
};

export type CommuniquesUpdateResponses = {
    200: CreateCommuniqueDto;
};

export type CommuniquesUpdateResponse = CommuniquesUpdateResponses[keyof CommuniquesUpdateResponses];

export type ImagesUploadImageData = {
    body: {
        image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/images/upload';
};

export type ImagesUploadImageResponses = {
    201: ImageResponseDto;
};

export type ImagesUploadImageResponse = ImagesUploadImageResponses[keyof ImagesUploadImageResponses];

export type ImagesGetImageData = {
    body?: never;
    path: {
        filename: string;
    };
    query?: never;
    url: '/images/{filename}';
};

export type ImagesGetImageResponses = {
    /**
     * Returns an image file
     */
    200: Blob | File;
};

export type ImagesGetImageResponse = ImagesGetImageResponses[keyof ImagesGetImageResponses];

export type ImagesDeleteImageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/images/{id}';
};

export type ImagesDeleteImageResponses = {
    200: boolean;
};

export type ImagesDeleteImageResponse = ImagesDeleteImageResponses[keyof ImagesDeleteImageResponses];

export type ClientOptions = {
    baseUrl: string;
};