import { MigrationInterface, QueryRunner } from "typeorm";

export class DeletedAtColumns1791560000366 implements MigrationInterface {
    name = 'DeletedAtColumns1791560000366'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "guest" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_snapshot" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_response" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_form_variant" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_reviewer" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "tag" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "general_update_activity" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "general_update" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reminder_group" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_suite" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "follow_up_form" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "project" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_activity" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "oauth_account" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_link" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_entry" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "community" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "campaign" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "city" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mail" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "participant" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mms" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "external_share_target" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "share_url" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "contract" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "contract_event" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "friend" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user_away_range" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "post_tag" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_update" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_event" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_event_notif" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "unread_content" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "push" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mms_optout" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "event_log" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "daily_stats_record" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_stats_record" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_tag" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_mail_allowance" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_entry_action" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_template" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_batch" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_recipient" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waitlist_cohort" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "video" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ambassador_program_interaction" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ambassador_program_member" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ambassador_invite_goal" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_response_draft" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "custom_validator" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invite_message_template" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "experiment_assignment" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "forum_digest_log" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_form_assignment" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_cohort_decision_correction" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_cohort_decision" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_partnership_note" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_partnership_response" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "message_tracking" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "link_opening" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "custom_link" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "action_update_exposure" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "action_update_exposure" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "custom_link" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "link_opening" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "message_tracking" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_partnership_response" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_partnership_note" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_cohort_decision" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_cohort_decision_correction" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_form_assignment" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "forum_digest_log" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "experiment_assignment" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "invite_message_template" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "custom_validator" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "form_response_draft" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "ambassador_invite_goal" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "ambassador_program_member" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "ambassador_program_interaction" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "video" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_cohort" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_recipient" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_batch" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_email_template" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entry_action" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_mail_allowance" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_tag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_stats_record" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "daily_stats_record" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "event_log" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "mms_optout" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "push" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "unread_content" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_event_notif" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_event" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_update" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "post_tag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "user_away_range" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "friend" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "contract_event" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "contract" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "share_url" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "external_share_target" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "mms" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "participant" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "mail" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "city" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "campaign" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "community" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_entry" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "waitlist_link" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "oauth_account" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_activity" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "follow_up_form" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_suite" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "reminder_group" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "general_update" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "general_update_activity" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "tag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_reviewer" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "action_form_variant" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "form_response" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "form" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "form_snapshot" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "guest" DROP COLUMN "deletedAt"`);
    }

}
