name: Actionlint

on:
  workflow_call:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Workflows
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
