name: CI

on:
  pull_request:
    branches: [main, production]

jobs:
  typecheck:
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            server,
            common,
            shared,
            sharedweb,
            apps/frontend,
            apps/admin,
            apps/mobile,
          ]
    uses: ./.github/workflows/typecheck.yaml
    with:
      package: ${{ matrix.package }}

  test-unit:
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            server,
            common,
            shared,
            sharedweb,
            apps/frontend,
            apps/admin,
            apps/mobile,
          ]
    uses: ./.github/workflows/test-unit.yaml
    with:
      package: ${{ matrix.package }}

  test-backend-e2e:
    uses: ./.github/workflows/test-backend-e2e.yaml

  migrations-drift-check:
    uses: ./.github/workflows/migrations-drift-check.yaml

  mobile-fingerprint-check:
    uses: ./.github/workflows/mobile-fingerprint-check.yaml
    secrets:
      SLACK_WEBHOOK_URL_DEPLOYMENT: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOYMENT }}
